#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/datahub.ls -> dist/datahub.js ..."
./node_modules/.bin/lsc -cp --no-header src/datahub.ls > dist/datahub.js
echo "minifying datahub.js ..."
./node_modules/.bin/terser dist/datahub.js > dist/datahub.min.js

echo "build src/sharehub.ls -> dist/sharehub.js ..."
./node_modules/.bin/lsc -cp --no-header src/sharehub.ls > dist/sharehub.js
echo "minifying sharehub.js ..."
./node_modules/.bin/terser dist/sharehub.js > dist/sharehub.min.js

echo "browserifying datahub ..."
./node_modules/.bin/browserify \
  --standalone datahub \
  -g unassertify \
  -g envify \
  -g uglifyify \
  -p browser-pack-flat/plugin \
  ./dist/datahub.js \
  | ./node_modules/.bin/terser > dist/datahub.bundle.min.js

echo "browserifying sharehub ..."
./node_modules/.bin/browserify \
  --standalone sharehub \
  -g unassertify \
  -g envify \
  -g uglifyify \
  -p browser-pack-flat/plugin \
  ./dist/sharehub.js \
  | ./node_modules/.bin/terser > dist/sharehub.bundle.min.js

echo "Copy dist/ to web/ ..."
rm -rf web/static/assets/lib/@plotdb/datahub/dev
mkdir -p web/static/assets/lib/@plotdb/datahub/dev
cp -R dist/* web/static/assets/lib/@plotdb/datahub/dev/
echo "done."

