#!/usr/bin/env bash
rm -rf dist
mkdir -p dist
echo "build src/datahub.ls -> dist/datahub.js ..."
./node_modules/.bin/lsc -cp --no-header src/datahub.ls > dist/datahub.js
echo "minifying datahub.js ..."
./node_modules/.bin/terser dist/datahub.js > dist/datahub.min.js

echo "build src/sharehub.ls -> dist/sharehub.js ..."
./node_modules/.bin/lsc -cp --no-header src/sharehub.ls > dist/sharehub.js
echo "minifying sharehub.js ..."
./node_modules/.bin/terser dist/sharehub.js > dist/sharehub.min.js

echo "build src/tabhub.ls -> dist/tabhub.js ..."
./node_modules/.bin/lsc -cp --no-header src/tabhub.ls > dist/tabhub.js
echo "minifying tabhub.js ..."
./node_modules/.bin/terser dist/tabhub.js > dist/tabhub.min.js

cat dist/datahub.js dist/sharehub.js dist/tabhub.js > dist/index.js
cat dist/datahub.min.js dist/sharehub.min.js dist/tabhub.min.js > dist/index.min.js

#echo "browserifying datahub ..."
#./node_modules/.bin/browserify --no-bf \
#  --standalone datahub \
#  -g unassertify \
#  -g envify \
#  -g uglifyify \
#  -p browser-pack-flat/plugin \
#  ./dist/datahub.js \
#  | ./node_modules/.bin/terser > dist/datahub.bundle.min.js
#
#echo "browserifying sharehub ..."
#./node_modules/.bin/browserify --no-bf \
#  --standalone sharehub \
#  -g unassertify \
#  -g envify \
#  -g uglifyify \
#  -p browser-pack-flat/plugin \
#  ./dist/sharehub.js \
#  | ./node_modules/.bin/terser > dist/sharehub.bundle.min.js

echo "Copy dist/ to web/ ..."
rm -rf web/static/assets/lib/@plotdb/datahub/dev
mkdir -p web/static/assets/lib/@plotdb/datahub/dev
cp -R dist/* web/static/assets/lib/@plotdb/datahub/dev/
echo "done."

