version: "3.8"
services:
  web:
    image: "datahub-backend:latest"
    ports:
      - 15100:5100
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
  db:
    image: "datahub-db:latest"
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=pg
      - POSTGRES_PASSWORD=pg
      - POSTGRES_DB=pg
